version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_stockify
    restart: always
    environment:
      POSTGRES_USER: stockify_user
      POSTGRES_PASSWORD: stockify_pass
      POSTGRES_DB: stockify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: stockify_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
