"""Refactor the space reserved for the string in the database.

Revision ID: 2c769ac78b6a
Revises: 834a8b09269a
Create Date: 2025-03-19 19:17:04.365600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c769ac78b6a'
down_revision: Union[str, None] = '834a8b09269a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'max_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('alert', 'min_message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('client', 'identifier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('client', 'contact',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('client', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('client', 'address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('ix_client_identifier', table_name='client')
    op.create_index(op.f('ix_client_identifier'), 'client', ['identifier'], unique=True)
    op.add_column('product', sa.Column('kit_id', sa.Integer(), nullable=True))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('product', 'serial_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('product', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('product', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'https://stockifystorage.s3.us-east-1.amazonaws.com/user_profiles/Flux_Dev_A_stylized_icon_for_a_modern_storage_company_featurin_1.jpeg'::character varying"))
    op.drop_index('ix_product_serial_number', table_name='product')
    op.create_index(op.f('ix_product_serial_number'), 'product', ['serial_number'], unique=False)
    op.create_unique_constraint('uq_serial_warehouse', 'product', ['serial_number', 'warehouse_id'])
    op.drop_constraint('product_product_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product', ['kit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'product_id')
    op.alter_column('warehouse', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('warehouse', 'address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouse', 'address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('warehouse', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('product', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_product_id_fkey', 'product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_serial_warehouse', 'product', type_='unique')
    op.drop_index(op.f('ix_product_serial_number'), table_name='product')
    op.create_index('ix_product_serial_number', 'product', ['serial_number'], unique=True)
    op.alter_column('product', 'image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True,
               existing_server_default=sa.text("'https://stockifystorage.s3.us-east-1.amazonaws.com/user_profiles/Flux_Dev_A_stylized_icon_for_a_modern_storage_company_featurin_1.jpeg'::character varying"))
    op.alter_column('product', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('product', 'serial_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('product', 'kit_id')
    op.drop_index(op.f('ix_client_identifier'), table_name='client')
    op.create_index('ix_client_identifier', 'client', ['identifier'], unique=False)
    op.alter_column('client', 'address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('client', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('client', 'contact',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('client', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('client', 'identifier',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('alert', 'min_message',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('alert', 'max_message',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
