"""add stripe fields to user

Revision ID: 4114b69e30d6
Revises: ab772645dabd
Create Date: 2025-05-11 09:59:31.189858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4114b69e30d6'
down_revision: Union[str, None] = 'ab772645dabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sa.String(length=150), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'user', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
