"""Add crate alert table

Revision ID: 51a8eb6fc9ac
Revises: bbbce8bf4a0e
Create Date: 2025-03-17 20:04:10.241410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a8eb6fc9ac'
down_revision: Union[str, None] = 'bbbce8bf4a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_message', sa.String(length=500), nullable=True),
    sa.Column('min_message', sa.String(length=500), nullable=True),
    sa.Column('Read', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_quantity >= 0', name='check_max_quantity_non_negative'),
    sa.CheckConstraint('min_quantity >= 0', name='check_min_quantity_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_date'), 'alert', ['date'], unique=False)
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_date'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
