"""Add an identifier column to the Transaction model and make the client_id column nullable.

Revision ID: 5577ee5ef00c
Revises: 60157cebe055
Create Date: 2025-04-22 21:01:22.768858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5577ee5ef00c'
down_revision: Union[str, None] = '60157cebe055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('identifier', sa.String(length=100), nullable=False))
    op.alter_column('transaction', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_transaction_identifier'), 'transaction', ['identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_identifier'), table_name='transaction')
    op.alter_column('transaction', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transaction', 'identifier')
    # ### end Alembic commands ###
