"""Add crate table product

Revision ID: 5903fd86716e
Revises: 394ee5f5f7ff
Create Date: 2025-03-16 10:37:12.497354

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5903fd86716e'
down_revision: Union[str, None] = '394ee5f5f7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('serial_number', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('category', sa.String(length=255), nullable=True),
                    sa.Column('image_url', sa.String(length=500),
                              server_default='https://stockifystorage.s3.us-east-1.amazonaws.com/user_profiles/Flux_Dev_A_stylized_icon_for_a_modern_storage_company_featurin_1.jpeg',
                              nullable=True),
                    sa.Column('warehouse_id', sa.Integer(), nullable=True),
                    sa.CheckConstraint('price >= 0', name='check_price_non_negative'),
                    sa.CheckConstraint('quantity >= 0', name='check_quantity_non_negative'),
                    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_quantity'), 'product', ['quantity'], unique=False)
    op.create_index(op.f('ix_product_serial_number'), 'product', ['serial_number'], unique=True)
    op.alter_column('warehouse', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('warehouse', 'phone',
                    existing_type=sa.VARCHAR(length=20),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.create_index(op.f('ix_warehouse_id'), 'warehouse', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_name'), 'warehouse', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_name'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_id'), table_name='warehouse')
    op.alter_column('warehouse', 'phone',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=20),
                    existing_nullable=True)
    op.alter_column('warehouse', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_index(op.f('ix_product_serial_number'), table_name='product')
    op.drop_index(op.f('ix_product_quantity'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
