"""Create relationship User/Clients.

Revision ID: 60157cebe055
Revises: 2c769ac78b6a
Create Date: 2025-04-21 18:41:31.448025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60157cebe055'
down_revision: Union[str, None] = '2c769ac78b6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    # ### end Alembic commands ###
