"""Refactor user model stripe_subscription_status: bolean


Revision ID: 6393994345b5
Revises: 0c88ff742791
Create Date: 2025-05-23 20:33:44.704949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6393994345b5'
down_revision: Union[str, None] = '0c88ff742791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_subscription_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_subscription_status')
    # ### end Alembic commands ###
