"""Refactor transaction_products model

Revision ID: 6c1244745704
Revises: 5577ee5ef00c
Create Date: 2025-04-26 10:50:06.230822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1244745704'
down_revision: Union[str, None] = '5577ee5ef00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_products',
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='transaction_products_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_products_transaction_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id', 'product_id', name='transaction_products_pkey')
    )
    # ### end Alembic commands ###
