"""Add column product_id in product table

Revision ID: 834a8b09269a
Revises: d22d6c8030ab
Create Date: 2025-03-19 18:23:43.215862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834a8b09269a'
down_revision: Union[str, None] = 'd22d6c8030ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'product_id')
    # ### end Alembic commands ###
