"""Edit ForeignKey client_id in trasaction table

Revision ID: bbbce8bf4a0e
Revises: 5cfc5df86ed5
Create Date: 2025-03-16 20:23:47.550394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbce8bf4a0e'
down_revision: Union[str, None] = '5cfc5df86ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_client_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_client_id_fkey', 'transaction', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
