"""add stripe stripe_subscription_status

Revision ID: cd9002fe3250
Revises: 4114b69e30d6
Create Date: 2025-05-11 10:58:14.808606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9002fe3250'
down_revision: Union[str, None] = '4114b69e30d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_subscription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_subscription_status')
    # ### end Alembic commands ###
