"""Add alert constraint in min max quantity column

Revision ID: d22d6c8030ab
Revises: 51a8eb6fc9ac
Create Date: 2025-03-17 20:45:24.478546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22d6c8030ab'
down_revision: Union[str, None] = '51a8eb6fc9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('read', sa.Boolean(), nullable=False))
    op.alter_column('alert', 'min_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('alert', 'Read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('Read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('alert', 'min_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('alert', 'read')
    # ### end Alembic commands ###
